### ISSUE TITLE
False Positive Malware

### ISSUE THREAD

**Issue by moymoussan** [TheSainEyereg/flipper-pc-monitor#2]
Your windows companion app is marked as **malicious** on VT https://www.virustotal.com/gui/file/509b73ddf2ded95fcbc08864aadd7d5a0e557e1d6065e9f35815b9add90ecc67
![IMG_1537](https://github.com/TheSainEyereg/flipper-pc-monitor/assets/66051741/d088e39d-b43a-4a67-b66f-a1e6c04c1cfa)

**Comment by TheSainEyereg** [comment]
Answered in https://github.com/TheSainEyereg/flipper-pc-monitor-backend/issues/3
